import tweepy
import random
import time
import os
from os import environ


theList = [
"I'm Lil Tay-K, I don't think you want no action,",
"(Gang, gang),",
"You want action, you get turned into past tense",
"Your boys deep? Well, let's get to subtractin",
"Smith & Wesson made my 9 with some compassion",
"fuck a beat, I was tryna beat a case",
"I was tryna beat a case",
"fuck a beat",
"I ain't beat that case",
"bitch I did the race",
"where I nut? Shorty face",
"where I nut?",
"Eli blast crackin' 4s like a vase",
"We tryna see a hunnit bands in our face",
"rob a nigga shoes, rob a nigga lace",
"Do the dash then I go out theBitch, ",
"I'm drawin' doodles, Tay-K, paint the way way",
"I'm drawin' doodles",
"(You're a simp)",
"Choppa tear your dudies into fish fillet",
"(Lil bitch)",
"we cookin' up, boy, you don't wanna go dat way",
"we make her dance, Michael Jackson",
"you get robbed for a fraction",
"Ran up with some ho",
"and he ran off as a ghost",
"Chopper with a stock, and a dick, and a scope",
"I'm woke",
"Tay-K, now I'm woke",
"Come here, bitch, throat, oh, oh, oh, oh",
"Try to play me like a pussy nigga and it won't work",
"Choppa with the stock, it's gon' kick, but it won't hurt",
"Turn this bitch sideways",
"rip him like some homework",
"Sneak up in his trap under the bed like a monster",
"Today you're not a trap-star",
"today you are a donor",
"I don't wanna cool it with the thot",
"I'm tryna bone her",
"I made a movie with a opp thot",
"She got Stussy on, that bitch basic and this won't work",
"Every slug hot, like a rapper at a concert",
"OG cookies and pussy niggas 'cause I do both",
"I said, Yes dentist said, Are you a smoker?",
"I asked her what the dick did, 'It murder' she wrote",
"'It murder' she wrote",
"she wanna give me more head",
"but my dick hurt her throat",
"you ain't runnin', you gon' float",
"She don't like Bloods",
"Coppers pull us over then we runnin' like a ho",
"And if they get too close"
"we get to dumpin' like a hoe",
"Have 'em doctors cuttin' heads",
"like a pumpkin in this ho",
"my whole gang stackin' like a bunk bed in this ho",
"Five times seven bullets rip you apart",
"Beep, beep",
"Gang, gang, gang",
"You know how the fuck we rockin' man",
"Free Tay-K",
"Gang",
"you was on some opp shit",
"I was cruisin' down a nigga block with the chopstick",
"now I need a rock bitch",
"We want beef, not veggies, not squash, bitch",
"that boy like to talk (gang)",
"we pop out with mops",
"You gon' shoot a little",
"we gon' shoot a lot",
"I rock out with the chop",
"I rock very hard (very hard)",
"She thought it was my cock",
"my Glock very hard",
"She thought it was my cock but my Glock very hard",
"School was very hard (gang)",
"bitch, I'm very hard (gang)",
"I'm very hard",
"Tay-K very hard",
"Tay-K fairly odd",
"chopper with a blade, 'cause my bitch goth",
"1911",
"Ma I'll leave you with a scar",
"My mama so hard",
"my daddy go hard",
"This thooka is my wand",
"Chopper with a blade",
"it's gon' rip you apart",
"You's a monkey nigga, so we knock your tree apart",
"Bullets aim far, bullets aim far",
"Rugrat shit, man",
"You already know how the fuck we rocking",
"I was cruisin' down the street, four deep",
"Three bitches, one yoppa on me",
"And the yoppa might as well be a fiend",
"'Cause it got two arms and some feet",
"'Cause it wake up in the morning and it eat",
"R.I.P. Eazy-E (gang!)",
"Let me hush, that’s between him and me",
"Call a hitter, 'cause he gon shoot for free",
"(yurr heard)",
"(love me)",
"I love my choppa and I think it love me",
"I love my choppa",
"I let that bitch do what it please",
"Choppa with extensions",
"pussy boy get on your knees",
"Money counter count it up, fffff, beep",
"fffff, beep",
"I don’t tote no choppa",
"bitch the choppa tote me",
"I might just pop ya",
"Yoppa have him Blood walkin' on the scene",
"blood poppin' out yo jeans",
"Tote F&N Five-Seven but I'm 16",
"I'm 16",
"He think he hard, well, that choppa beat his meat (eugh)",
"beat his meat (eugh)",
"My momma insane",
"My daddy OG",
"I’m EBK",
"So I’m insane",
"I don’t know what to think",
"I’ll put anything to sleep",
"I love my choppa and her parents wanna meet",
"we can get it cracking",
"Double R full shit",
"EBK, bitch, ATK, bitch, ABK bitch",
"Lil' Tay-K, I'm 'bout that action",
"Bitch tryna get wife'd",
"my dick she can get up",
"Smoke about a thot",
"if you want it, we could get up",
"Locked down on a boot, but lil' Tay-K had to get up",
"Bitch want my loot",
"what she want, she can't get none ",
"Chicken noodle soup",
"choppa cook a nigga shit up",
"I don't want no love",
"I'm tryna get a nut",
"And my bullets blue",
"lil' bitch yeah they Cripped up",
"(My bullets Cripped up)",
"But I'm with my blood",
"swear to god we gon' rip some",
"I'm a Rugrat, if I want it, I'ma get some",
"Got my finger prints on some hollow-tips",
"She drinks lemonade",
"I drink Lipton",
"Juggs are Minute Maid",
"She drinks lemonade, I drink Lipton (I drink lipton)",
"Call up Dee, VIP",
"we might have to kick some",
"Lipton (Beep)",
"Choppa put bullets in your system",
"I can't get caught lackin",
"it's not in my system",
"Codeine, promethazine, in my fuckin' system",
"I'm just tryna ball like a motherfuckin' Piston",
"I'm just tryna ball",
"Shining like I'm Megaman",
"I smoke mega, man",
"I'm Megaman",
"Don't come at the youth",
"Niggas quick to change",
"Niggas quick to change, uh, y'all some Bruce Wayne",
"Bruce Wayne",
"(pew, pew, pew)",
"If he act mysterious he get hit with my ray",
"And if you was curious, yes, I'm Tay-K",
"I'm not on time with everything",
"I look at your gang",
"get my 40 and I aim",
"Marks on his head",
"Marks on his head, now he looking like Aang",
"I don't wanna smooch",
"I really want the brain",
"I just hit a stain now your bitch wanna claim",
"Just opened up your pack and it better be stank",
"Pop up out the cut",
"Pop up out the cut, we get up wit' ya",
"Smoke him down like a damn Swisher",
"I need my bands bigger",
"thought she was a keeper",
"my mans hit her",
"my mans hit her, I let Blast switch her",
"my mans hit her so I gotta switch her",
"Call up Bay-Bay, yeah, yeah, he's a class ditcher",
"Call up Blast, yeah, yeah, he's a ass kicker",
"Call a shooter, yeah, I gotta blast",
"I gotta blast",
"Gotta blast, leave you in the past",
"(hahaha)",
"she say gimme head, bitch, after you",
"Foenem, go in first, I go after you",
"You'll-you'll-you'll",
"you'll get robbed for your flashy shoes",
"gimme head",
"that glizzy don't get passed to you",
"you wouldn't even shoot, if you had to shoot",
"wanna show his ass like a baboon"
"(like a fucking baboon)",
"Now he's a hashtag, now he's a tattoo",
"(now you're a tattoo)",
"(in a fucking bathroom)",
"You get ate like fast food",
"You won't walk, you gon' crawl away like a raccoon",
"(like a fucking raccoon)",
"Hands in the air like a statue",
"(fucking classroom)",
"See through you like a glassroom",
"1, 2, 3, call Blast for you",
"The choppa stock detachable",
"You want beef?",
"You want beef? Just ask dude number nine my chest",
"my ass, dude (gang)",
"I tote the gat 'cause I have to",
"you tote it 'cause it's fashionable",
"Tears in the water",
"we pop out in the afternoon",
"This Gosha international",
"This Gosha international, touch and bullets come after you",
"I was splurgin' at North Park, tryna look rich",
"tryna look rich",
"Could've bought an ass for my motherfuckin' bitch",
"Free Santana Sage",
"On my momma",
"I won't ever flip the page, bitch",
"I'm stickin' to the script",
"Bitch, I'm half your fuckin' age",
"Old ass niggas lame",
"yo' aim ain't shit",
"Bitch I keep the Smith like my name Brad Pitt",
"my name Brad Pitt",
"22 shots, clip look like my dick",
"I get lit (Yuh)",
"Bitch I'm loadin' up this Cobra while you loadin' up that diss",
"what's the addy to your crib?",
"And if you run up on me like a Beyblade, I rip",
"Lil Tay-K with the shits",
"I never duck a opp, unless he is a snitch",
"I can't even resist",
"And I still got opps",
"cause I'm still hittin' licks",
"I'm steady on the clock",
"And the feds want my head, I-",
"I'm always finessin', I can never ever stop",
"If a nigga try to press me, like a soda I pop (Pop)",
"If 12 pull me over, on my momma I'ma run",
"Cause it's BB on my belt, but its hollows in my gun",
"I'm out here in the field, and I do this shit for fun",
"I could never miss one",
"Mama told me, Never lose 'cause, baby, you're winner",
"I was lurkin' 'round his block, he was lurkin' on my Twitter",
"on my Twitter",
"Tay-K babysitter",
"At the trap with the Glocks",
"I was just tryna shine like some mothafuckin' glitter (homosexual)",
"I was under rugs with my Cuz, tryna rob a plug",
"she want love, I ain't show her none",
"I said Bitch, I'm a rugrat, I don't know how to love back",
"Them QP's and them dub sacks, girl, that's where my love at",
"Choppa in the trunk, Glock in my hand",
"If a nigga run up on me, it's a wrap like Saran"
"it's a wrap like Saran (gang, it's a wrap)",
"I be totin' yoppas, bitch, that's everyday",
"Let my white bitch hold the yoppa, call her Mary Kay.",
"call her Mary Kay. (Mary Kay.) shoutout Abby",
"I can't fuck with ganja,",
"When my spot get hot like lava, gotta stay away",
"But I'm still on Fabiana, can't make up my brain",
"(my fuckin brain)",
"Let me know if you want it",
"Two pistols, one Tay-K, call me Tay-K Max Payne ",
"try Lil' Tay-K, it's gon' be his last day",
"If you not talkin' 'bout smoke, you could go dat way",
"(dat fucking way)",
"He think he hot, we put him out, where is the ash tray?",
"where is the ash tray?",
"I fucked yo' bitch on the first and the last date",
"I'm smoking dead opps out the ashtray",
"I also got some K.K. in my ashtray",
"Big glizzy knock yo' toupee (dat way, dat way)",
"you could go dat way (gang)",
"Big 30, ain't no .38",
"(gang, gang, beep!)",
"I was terrorizing",
"you was kickin' rocks,",
"I was finding juggs",
"Nemo, you was lost, nigga,",
"Get the work, get it tossed on the clock,",
"On the clock, need the Rollie wrist watch",
"I might do a lil' somethin', half-off,",
"Half-off, what you want?",
"But I'm still inside traffic with the Glocks",
"Why you niggas inside traffic? Get on the block,",
"Choppa turn you inside, backwards,",
"better get lost",
"She say, Tay-K, you remember it was awesome, man",
"Stupid bitch, I was rollin' like a log",
"Rolling like a log, bitch wanna jerk me off",
"what the fuck",
"lips are cod",
"call me Tay-K fraud",
"Hit his block with guitars, 'cause I rock",
"When I'm sipping Wock",
"I rock",
"You undercover like the jeans that I rock",
"get to clappin', like applause",
"Five times seven bullets rip you apart",
]

consumer_key = os.environ.get('consumer_key')
consumer_secret = os.environ.get('consumer_secret')
key = os.environ.get('key')
secret = os.environ.get('secret')




auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(key, secret)
api = tweepy.API(auth)


def botTweet():
    for element in theList:
        api.update_status(random.choice(theList))
        time.sleep(10)

botTweet()



